version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server-container
    command: ./server
    tty: true

  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client-container
    command: ./client
    tty: true
